version: "3.8"
services:
  server:
    build: ./src/server
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: ${MONGO_URI}/test
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongodb
  client:
    build: ./src/client
    ports:
      - "5173:5173"
    depends_on:
      - server