version: "3.8"
services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - net
  app:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      - database
volumes:
  mongodb_data_container:
networks:
    net:
